User.create!([
  {email: "admin@email.com", encrypted_password: "$2a$11$nhaIdARUTslZamvAF9HdYOMrpMrhDoz70eMJfdJyiz0d13MgUU6PK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 41, current_sign_in_at: "2016-09-08 04:56:01", last_sign_in_at: "2016-09-08 04:43:32", current_sign_in_ip: "::1", last_sign_in_ip: "::1", role: "admins"},
  {email: "mentor20@email.com", encrypted_password: "$2a$11$wSOFBqub/xgFX8qlaKMBm.4v6/Ac4.LU6eEgTGx8fP1z9sCUVWTIW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-09-01 02:58:56", last_sign_in_at: "2016-09-01 02:58:04", current_sign_in_ip: "::1", last_sign_in_ip: "::1", role: "student"},
  {email: "mentor40@email.com", encrypted_password: "$2a$11$JvyILYe/2yWePjcWzLP2pu9ZH6Ubr6usKwDQAVs/YYU2E/3d93xzO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, role: "mentors"},
  {email: "mentor50@email.com", encrypted_password: "$2a$11$SyRLEH2M/Zt0UzJUujABl.CLSaThFuMMmop96MYpM4GvIOUFSQqE2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, role: "mentors"},
  {email: "mentor@email.com", encrypted_password: "$2a$11$3HxZ99bCZPE1VvtyTzGaXuX1/mS0Tw2J0CPykT9MeY57A1ichE0JC", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 26, current_sign_in_at: "2016-09-07 22:54:00", last_sign_in_at: "2016-09-07 03:25:41", current_sign_in_ip: "::1", last_sign_in_ip: "::1", role: "mentors"},
  {email: "mentor10@email.com", encrypted_password: "$2a$11$HbnhwmWtgMlLGE0XMeryv.oWRRJMZS4q1r6EYiIQeMcyrpFYOhXS6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, role: "mentors"},
  {email: "student@email.com", encrypted_password: "$2a$11$dhFOojl/kfxKBI3r4IPjRu3MUoY5XUXhSFung9Za85MhXAPgFB6qO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 16, current_sign_in_at: "2016-09-08 00:35:24", last_sign_in_at: "2016-09-07 03:30:46", current_sign_in_ip: "::1", last_sign_in_ip: "::1", role: "students"},
  {email: "student50@email.com", encrypted_password: "$2a$11$1jQ8J8HclamcO4c7DLckPOtnd.u/dHd4l3AlAM6IG8p5Dyp0LTxeG", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, role: "students"},
  {email: "mentor11@email.com", encrypted_password: "$2a$11$SLfOIqAhpWDrtAb6dFKsHuZ1AFUFNS1JvaWYLSIXbtwXsxPBOJJZ2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-09-08 04:38:08", last_sign_in_at: "2016-09-08 00:08:13", current_sign_in_ip: "::1", last_sign_in_ip: "::1", role: "mentors"},
  {email: "mentor30@email.com", encrypted_password: "$2a$11$.Ka.fje.JqcHDy9s5iJZ2OhTLSX75uyObtFid0gZM0mnzW4sl/Xp6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-09-08 04:38:42", last_sign_in_at: "2016-09-08 04:38:42", current_sign_in_ip: "::1", last_sign_in_ip: "::1", role: "mentors"},
  {email: "student30@email.com", encrypted_password: "$2a$11$tCCWFanB4pXcEcvBet0HSOyF/7U0985CTuDvFV9rrAasFoyMWUNQ6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-09-08 04:40:38", last_sign_in_at: "2016-09-08 04:40:38", current_sign_in_ip: "::1", last_sign_in_ip: "::1", role: "students"},
  {email: "student40@email.com", encrypted_password: "$2a$11$PktDwGTPnALY27D/0fXDROTIpiqggPSQVtzWoioeV.M3jTY/6xMGq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-09-08 04:42:01", last_sign_in_at: "2016-09-08 04:42:01", current_sign_in_ip: "::1", last_sign_in_ip: "::1", role: "students"},
  {email: "student41@email.com", encrypted_password: "$2a$11$qmCoE72dLW6U2xBFz8bqsOlSk6fCts9hoMx1sDxsXcn4PqydR/vse", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-09-08 04:54:18", last_sign_in_at: "2016-09-08 04:54:18", current_sign_in_ip: "::1", last_sign_in_ip: "::1", role: "students"}
])
Mentor.create!([
  {company: "canceriqd", industry: "healthcaree", website: "www.ciqf", first_name: "Milo", last_name: "bob", phone_number: "9879879876", user_id: 6, contact_email: nil},
  {company: "banker", industry: "finance", website: "www.banker.com", first_name: "Ken", last_name: "Bakerbad", phone_number: "2342342345", user_id: 20, contact_email: nil},
  {company: "this company", industry: "healthcare", website: "www.company", first_name: "stan", last_name: "theman", phone_number: "12312233342", user_id: 22, contact_email: nil},
  {company: "ustrust", industry: "newpapers", website: "www.ustrust.com", first_name: "kim", last_name: "sirbud", phone_number: "1231231234", user_id: 24, contact_email: nil}
])
Profile.create!([
  {body: "a lot of text will go here. things all about myself", availability_array: [], student_id: nil, mentor_id: nil},
  {body: "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", availability_array: [], student_id: nil, mentor_id: nil},
  {body: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their ", availability_array: [], student_id: nil, mentor_id: nil},
  {body: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.", availability_array: [], student_id: 3, mentor_id: nil},
  {body: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their", availability_array: [], student_id: 2, mentor_id: nil},
  {body: "this is text that goes here", availability_array: [], student_id: nil, mentor_id: 48},
  {body: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary", availability_array: [], student_id: 4, mentor_id: nil},
  {body: "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem ", availability_array: [], student_id: nil, mentor_id: 49},
  {body: "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", availability_array: [], student_id: nil, mentor_id: nil},
  {body: "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software.", availability_array: [], student_id: nil, mentor_id: nil},
  {body: "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software.", availability_array: [], student_id: nil, mentor_id: 46},
  {body: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their GGGGGGG", availability_array: [], student_id: nil, mentor_id: nil},
  {body: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.", availability_array: [], student_id: nil, mentor_id: 47},
  {body: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.", availability_array: [], student_id: nil, mentor_id: nil},
  {body: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their", availability_array: [], student_id: nil, mentor_id: nil},
  {body: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary", availability_array: [], student_id: 5, mentor_id: nil},
  {body: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.", availability_array: [], student_id: 6, mentor_id: nil}
])
Student.create!([
  {school: "East high school", grade: "", gender: "female", first_name: "candy", last_name: "treetops", phone_number: "9879879876", user_id: 21, contact_email: nil},
  {school: "West Side High School", grade: "10", gender: "female", first_name: "rachela", last_name: "vichorek", phone_number: "5556667878", user_id: 5, contact_email: nil},
  {school: "west high school", grade: "11", gender: "male", first_name: "frank", last_name: "boostrap", phone_number: "9879879876", user_id: 27, contact_email: nil},
  {school: "south high school", grade: "9", gender: "male", first_name: "payton", last_name: "manning", phone_number: "1231231234", user_id: 28, contact_email: nil},
  {school: "north east middle school", grade: "8", gender: "female", first_name: "betty", last_name: "chui", phone_number: "3453453456", user_id: 30, contact_email: nil}
])
